name: Example checks

on:
  push:
    branches:
      [main, staging, deployment/*]

jobs:
  failing_check:
    runs-on: ubuntu-latest

    steps:
      - run: |
          exit 1

  passing_check:
    runs-on: ubuntu-latest

    steps:
      - run: |
          exit 0