name: merge bot

on:
  pull_request:
    types:
      - labeled
      - ready_for_review
      - review_request_removed
      - review_requested
      - synchronize
      - unlabeled
  pull_request_review:
    types:
      - dismissed
      - submitted

jobs:
  # This workflow contains a single job called "build"
  merge-bot:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: ryansingman/merge-bot@0.0.0-alpha
        with:
          dependent_checks: "failing_check,passing_check"
          blocking_label: "block-merge"
          merge_type: "fast-forward"
